INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_CHANNELMODEL2 ChannelModel2)

FIND_PATH(
    CHANNELMODEL2_INCLUDE_DIRS
    NAMES ChannelModel2/api.h
    HINTS $ENV{CHANNELMODEL2_DIR}/include
        ${PC_CHANNELMODEL2_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    CHANNELMODEL2_LIBRARIES
    NAMES gnuradio-ChannelModel2
    HINTS $ENV{CHANNELMODEL2_DIR}/lib
        ${PC_CHANNELMODEL2_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CHANNELMODEL2 DEFAULT_MSG CHANNELMODEL2_LIBRARIES CHANNELMODEL2_INCLUDE_DIRS)
MARK_AS_ADVANCED(CHANNELMODEL2_LIBRARIES CHANNELMODEL2_INCLUDE_DIRS)

